create extension if not exists pgcrypto;

create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  title text not null,
  company text not null,
  location text not null,
  salary text,
  salary_min integer,
  salary_max integer,
  role_type text,
  source text,
  url text,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  desired_title text,
  location text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.saved_jobs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  job_id bigint not null references public.jobs(id) on delete cascade,
  saved_at timestamptz not null default now(),
  unique (user_id, job_id)
);

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  stripe_customer_id text unique,
  stripe_subscription_id text unique,
  plan text not null default 'free',
  status text not null default 'inactive',
  current_period_end timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists jobs_location_idx on public.jobs (location);
create index if not exists jobs_role_type_idx on public.jobs (role_type);
create index if not exists jobs_created_at_idx on public.jobs (created_at desc);
create index if not exists saved_jobs_user_id_idx on public.saved_jobs (user_id);
create index if not exists saved_jobs_job_id_idx on public.saved_jobs (job_id);
create index if not exists subscriptions_user_id_idx on public.subscriptions (user_id);

alter table public.jobs enable row level security;
alter table public.user_profiles enable row level security;
alter table public.saved_jobs enable row level security;
alter table public.subscriptions enable row level security;

create policy "Anyone can read jobs" on public.jobs for select using (true);

create policy "Users can read own profile" on public.user_profiles for select using (auth.uid() = user_id);
create policy "Users can update own profile" on public.user_profiles for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can insert own profile" on public.user_profiles for insert with check (auth.uid() = user_id);

create policy "Users can read own saved jobs" on public.saved_jobs for select using (auth.uid() = user_id);
create policy "Users can insert own saved jobs" on public.saved_jobs for insert with check (auth.uid() = user_id);
create policy "Users can delete own saved jobs" on public.saved_jobs for delete using (auth.uid() = user_id);

create policy "Users can read own subscriptions" on public.subscriptions for select using (auth.uid() = user_id);

create policy "Service role can manage jobs" on public.jobs for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "Service role can manage profiles" on public.user_profiles for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "Service role can manage saved jobs" on public.saved_jobs for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "Service role can manage subscriptions" on public.subscriptions for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
