-- Seed data for jobs table
-- This creates 10 realistic job postings with varied titles, locations, and salaries

INSERT INTO jobs (source, external_id, title, company, location, salary_min, salary_max, salary_text, type, url, posted_at, raw) VALUES
(
    'manual_seed',
    'seed-001',
    'Senior Software Engineer',
    'TechCorp Solutions',
    'San Francisco, CA',
    150000,
    200000,
    '$150k - $200k',
    'Full-time',
    'https://example.com/jobs/senior-software-engineer-1',
    NOW() - INTERVAL '2 days',
    '{"description": "Build scalable web applications", "skills": ["Python", "React", "AWS"]}'::jsonb
),
(
    'manual_seed',
    'seed-002',
    'Frontend Developer',
    'Digital Innovations Inc',
    'New York, NY',
    120000,
    160000,
    '$120k - $160k',
    'Full-time',
    'https://example.com/jobs/frontend-developer-2',
    NOW() - INTERVAL '1 day',
    '{"description": "Create beautiful user interfaces", "skills": ["JavaScript", "TypeScript", "Next.js"]}'::jsonb
),
(
    'manual_seed',
    'seed-003',
    'DevOps Engineer',
    'Cloud Systems Co',
    'Austin, TX',
    130000,
    170000,
    '$130k - $170k',
    'Full-time',
    'https://example.com/jobs/devops-engineer-3',
    NOW() - INTERVAL '3 days',
    '{"description": "Manage cloud infrastructure", "skills": ["Kubernetes", "Docker", "Terraform"]}'::jsonb
),
(
    'manual_seed',
    'seed-004',
    'Product Manager',
    'StartupXYZ',
    'Remote',
    140000,
    180000,
    '$140k - $180k',
    'Full-time',
    'https://example.com/jobs/product-manager-4',
    NOW() - INTERVAL '5 days',
    '{"description": "Drive product strategy and roadmap", "skills": ["Product Management", "Agile", "Analytics"]}'::jsonb
),
(
    'manual_seed',
    'seed-005',
    'Data Scientist',
    'Analytics Pro',
    'Seattle, WA',
    135000,
    185000,
    '$135k - $185k',
    'Full-time',
    'https://example.com/jobs/data-scientist-5',
    NOW() - INTERVAL '4 days',
    '{"description": "Analyze data and build ML models", "skills": ["Python", "SQL", "Machine Learning"]}'::jsonb
),
(
    'manual_seed',
    'seed-006',
    'Backend Developer',
    'Enterprise Solutions LLC',
    'Boston, MA',
    125000,
    165000,
    '$125k - $165k',
    'Full-time',
    'https://example.com/jobs/backend-developer-6',
    NOW() - INTERVAL '6 days',
    '{"description": "Build robust API services", "skills": ["Node.js", "PostgreSQL", "Redis"]}'::jsonb
),
(
    'manual_seed',
    'seed-007',
    'UX Designer',
    'Creative Agency',
    'Los Angeles, CA',
    110000,
    145000,
    '$110k - $145k',
    'Full-time',
    'https://example.com/jobs/ux-designer-7',
    NOW() - INTERVAL '7 days',
    '{"description": "Design user-centered experiences", "skills": ["Figma", "User Research", "Prototyping"]}'::jsonb
),
(
    'manual_seed',
    'seed-008',
    'Full Stack Engineer',
    'Growth Ventures',
    'Chicago, IL',
    145000,
    190000,
    '$145k - $190k',
    'Full-time',
    'https://example.com/jobs/fullstack-engineer-8',
    NOW() - INTERVAL '1 day',
    '{"description": "Work across the entire stack", "skills": ["React", "Python", "GraphQL"]}'::jsonb
),
(
    'manual_seed',
    'seed-009',
    'Mobile Developer',
    'AppBuilders Inc',
    'Denver, CO',
    115000,
    155000,
    '$115k - $155k',
    'Full-time',
    'https://example.com/jobs/mobile-developer-9',
    NOW() - INTERVAL '8 days',
    '{"description": "Build native mobile applications", "skills": ["React Native", "iOS", "Android"]}'::jsonb
),
(
    'manual_seed',
    'seed-010',
    'Engineering Manager',
    'Scale Tech',
    'San Diego, CA',
    160000,
    210000,
    '$160k - $210k',
    'Full-time',
    'https://example.com/jobs/engineering-manager-10',
    NOW() - INTERVAL '2 days',
    '{"description": "Lead engineering teams", "skills": ["Leadership", "Technical Strategy", "Mentoring"]}'::jsonb
);
